### ISSUE TITLE
vite +vue3 Error

### ISSUE THREAD

**Issue by patrick-Xu** [joeldenning/vite-single-spa-example#3]
Can I have the example code for configuration property of parent applcation ? My console information is following uncaught TypeError: application 'app1' died in status LOADING_SOURCE_CODE: Cannot convert undefined or null to object
![image](https://user-images.githubusercontent.com/40697435/117159249-b4af2480-adf2-11eb-8990-6f15aa130c78.png)

**Comment by internettrans** [comment]
Sure, you'll need to use `import(/* webpackIgnore: true */ 'http://localhost:3000/src/main.js')` rather than `System.import()`.

I created https://github.com/joeldenning/vite-single-spa-root-config which shows this, and also added [this documentation](c80194d13db2b70b62c9c5b8a30e47ab2639611a) explaining it a bit.

I also upgraded this example to use Vite 2
